name: Confluence Publisher                

on:
  push:
     tags: 
       - 'v*-bpa'                          
jobs:
    build:
  
      runs-on: ubuntu-latest              #paten
  
      steps:
      - uses: actions/checkout@v2         #paten
      - name: Set up JDK 1.8              #paten
        uses: actions/setup-java@v1       #paten
        with:
          java-version: 1.8               #paten
      - name: Build with Maven
        env:
          username: ${{ secrets.ID_AYUMEL}}
          password: ${{ secrets.PASS_AYUMEL}}
        run: mvn org.sahli.asciidoc.confluence.publisher:asciidoc-confluence-publisher-maven-plugin:publish --file pom.xml -Dusername=$username -Dpassword=$password
        # "--file pom.xml" tergantung tempat peletakan contoh di dalam dokumen "--file nama-document/pom.xml". dan juga penamaan pom dapat ditambahi untuk dokumen yang ingin di publish dalam confluence.
